import { useState, useContext, useEffect } from "react";
import { Download, Mail, TrendingUp, TrendingDown, Award, Calendar, Target, Zap, FileText, Share2, Printer, CheckCircle2, AlertCircle, BarChart3 } from "lucide-react";
import { TranslationContext } from "../App";

export default function Report({ habitData }) {
  const { t, currentLanguage, translating } = useContext(TranslationContext);
  
  const [timeframe, setTimeframe] = useState("all"); // 'all', '30days', '7days'
  const [exportFormat, setExportFormat] = useState("txt"); // 'txt', 'pdf', 'email'
  const [showShareModal, setShowShareModal] = useState(false);
  const [translatedText, setTranslatedText] = useState({});

  // Translation keys
  const translationKeys = {
    title: "Dental Report",
    subtitle: "Comprehensive analysis of your dental care habits",
    allTime: "All Time",
    last30Days: "Last 30 Days",
    last7Days: "Last 7 Days",
    totalDays: "Total Days",
    perfectDays: "Perfect Days",
    taskBreakdown: "Task Breakdown",
    morningBrushing: "Morning Brushing",
    nightBrushing: "Night Brushing",
    interdentalCare: "Interdental Care",
    outOfDays: "out of",
    days: "days",
    completionDistribution: "Completion Distribution",
    perfect: "Perfect Days",
    partial: "Partial Days",
    skipped: "Skipped Days",
    personalizedInsights: "Personalized Insights",
    weeklyTrend: "Weekly Trend",
    perfectDaysLower: "perfect days",
    shareReport: "Share Your Report",
    downloadReport: "Download Report",
    downloadDesc: "Save as text file for your dentist",
    emailReport: "Email Report",
    emailDesc: "Send directly to your dentist",
    printReport: "Print Report",
    printDesc: "Physical copy for appointments",
    shareWithDentist: "Share with Your Dentist",
    shareWithDentistDesc: "This report provides valuable insights for your next dental appointment. Your dentist can use this data to give you personalized recommendations!",
    vsPrevious: "vs previous",
    improving: "Improving",
    declining: "Declining",
    generated: "Generated",
    
    // Insight messages
    insightExcellent: "Excellent consistency! You're maintaining a strong routine.",
    insightGood: "Good progress! Try to complete all three tasks daily for best results.",
    insightImprovement: "Room for improvement. Set reminders to build consistency.",
    insightMorningNeeds: "Morning brushing needs attention. Consider setting an alarm.",
    insightFlossLower: "Flossing frequency is lower than brushing. Aim to match your brushing consistency.",
    insightImproved: "You've improved by {change}% compared to the previous period!",
    
    // Report header
    reportTitle: "SMILE STREAK DENTAL REPORT",
    reportLast7Days: "Last 7 Days",
    reportLast30Days: "Last 30 Days",
    reportAllTime: "All Time",
    reportSummary: "SUMMARY",
    reportTrackedDays: "Tracked Days",
    reportPerfectDays: "Perfect Days",
    reportPartialCompletion: "Partial Completion",
    reportSkippedDays: "Skipped Days",
    reportTaskBreakdown: "TASK BREAKDOWN",
    reportTrendAnalysis: "TREND ANALYSIS",
    reportChangeFromPrevious: "Change from previous period",
    reportStatus: "Status",
    reportKeyInsights: "KEY INSIGHTS",
    reportFooter: "This report was generated by Smile Streak\nShare with your dentist for personalized advice"
  };

  // Filter data by timeframe
  const getFilteredDates = () => {
    const dates = Object.keys(habitData).filter((k) => !k.startsWith("__"));
    
    if (timeframe === "all") return dates;
    
    const now = new Date();
    const cutoff = new Date();
    
    if (timeframe === "7days") {
      cutoff.setDate(now.getDate() - 7);
    } else if (timeframe === "30days") {
      cutoff.setDate(now.getDate() - 30);
    }
    
    return dates.filter(date => new Date(date) >= cutoff);
  };

  const dates = getFilteredDates();
  let totalDays = dates.length;
  let morningCount = 0;
  let nightCount = 0;
  let flossCount = 0;
  let perfectDays = 0;
  let partialDays = 0;
  let skippedDays = 0;

  // Weekly breakdown
  const weeklyData = {};
  const monthlyData = {};

  dates.forEach((date) => {
    const d = habitData[date];
    if (!d) return;

    const completedTasks = [d.morning, d.night, d.floss].filter(Boolean).length;

    if (d.morning) morningCount++;
    if (d.night) nightCount++;
    if (d.floss) flossCount++;

    if (completedTasks === 3) perfectDays++;
    else if (completedTasks > 0) partialDays++;
    else skippedDays++;

    // Weekly tracking
    const weekKey = getWeekKey(new Date(date));
    if (!weeklyData[weekKey]) weeklyData[weekKey] = { perfect: 0, partial: 0, skipped: 0 };
    if (completedTasks === 3) weeklyData[weekKey].perfect++;
    else if (completedTasks > 0) weeklyData[weekKey].partial++;
    else weeklyData[weekKey].skipped++;

    // Monthly tracking
    const monthKey = new Date(date).toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
    if (!monthlyData[monthKey]) monthlyData[monthKey] = 0;
    if (completedTasks === 3) monthlyData[monthKey]++;
  });

  function getWeekKey(date) {
    const startOfYear = new Date(date.getFullYear(), 0, 1);
    const days = Math.floor((date - startOfYear) / (24 * 60 * 60 * 1000));
    const weekNum = Math.ceil((days + 1) / 7);
    return `Week ${weekNum}`;
  }

  const percent = (n) => totalDays ? Math.round((n / totalDays) * 100) : 0;

  // Calculate trends (compare to previous period)
  const getPreviousPeriodComparison = () => {
    if (timeframe === "all") return null;
    
    const now = new Date();
    const currentPeriodStart = new Date();
    const previousPeriodStart = new Date();
    const previousPeriodEnd = new Date();
    
    if (timeframe === "7days") {
      currentPeriodStart.setDate(now.getDate() - 7);
      previousPeriodStart.setDate(now.getDate() - 14);
      previousPeriodEnd.setDate(now.getDate() - 7);
    } else {
      currentPeriodStart.setDate(now.getDate() - 30);
      previousPeriodStart.setDate(now.getDate() - 60);
      previousPeriodEnd.setDate(now.getDate() - 30);
    }

    const allDates = Object.keys(habitData).filter((k) => !k.startsWith("__"));
    const previousDates = allDates.filter(date => {
      const d = new Date(date);
      return d >= previousPeriodStart && d < previousPeriodEnd;
    });

    let prevPerfect = 0;
    previousDates.forEach(date => {
      const d = habitData[date];
      if (d?.morning && d?.night && d?.floss) prevPerfect++;
    });

    const prevPercent = previousDates.length ? Math.round((prevPerfect / previousDates.length) * 100) : 0;
    const currentPercent = percent(perfectDays);
    const change = currentPercent - prevPercent;

    return { change, improving: change > 0 };
  };

  const trend = getPreviousPeriodComparison();

  // Load translations when language changes
  useEffect(() => {
    const loadTranslations = async () => {
      const translations = {};
      
      // Load main translations
      for (const [key, value] of Object.entries(translationKeys)) {
        translations[key] = await t(value);
      }
      
      setTranslatedText(translations);
    };
    
    loadTranslations();
  }, [currentLanguage, t]);

  // Generate insights with translations
  const getInsights = () => {
    const insights = [];

    if (percent(perfectDays) >= 80) {
      insights.push({ 
        type: "success", 
        text: translatedText.insightExcellent || translationKeys.insightExcellent, 
        icon: <Award className="w-5 h-5 text-yellow-500" /> 
      });
    } else if (percent(perfectDays) >= 50) {
      insights.push({ 
        type: "info", 
        text: translatedText.insightGood || translationKeys.insightGood, 
        icon: <TrendingUp className="w-5 h-5 text-blue-500" /> 
      });
    } else {
      insights.push({ 
        type: "warning", 
        text: translatedText.insightImprovement || translationKeys.insightImprovement, 
        icon: <AlertCircle className="w-5 h-5 text-orange-500" /> 
      });
    }

    if (percent(morningCount) < 50) {
      insights.push({ 
        type: "tip", 
        text: translatedText.insightMorningNeeds || translationKeys.insightMorningNeeds, 
        icon: <Target className="w-5 h-5 text-purple-500" /> 
      });
    }

    if (percent(flossCount) < percent(morningCount)) {
      insights.push({ 
        type: "tip", 
        text: translatedText.insightFlossLower || translationKeys.insightFlossLower, 
        icon: <Zap className="w-5 h-5 text-cyan-500" /> 
      });
    }

    if (trend && trend.improving) {
      const text = (translatedText.insightImproved || translationKeys.insightImproved).replace('{change}', trend.change);
      insights.push({ 
        type: "success", 
        text: text, 
        icon: <TrendingUp className="w-5 h-5 text-green-500" /> 
      });
    }

    return insights;
  };

  const insights = getInsights();

  // Export functions with translated content
  const reportText = `
${translatedText.reportTitle || translationKeys.reportTitle}
${timeframe === "7days" ? translatedText.reportLast7Days || translationKeys.reportLast7Days : timeframe === "30days" ? translatedText.reportLast30Days || translationKeys.reportLast30Days : translatedText.reportAllTime || translationKeys.reportAllTime}
${translatedText.generated || translationKeys.generated}: ${new Date().toLocaleDateString()}

═══════════════════════════════════════

${translatedText.reportSummary || translationKeys.reportSummary}
${translatedText.reportTrackedDays || translationKeys.reportTrackedDays}: ${totalDays}
${translatedText.reportPerfectDays || translationKeys.reportPerfectDays}: ${perfectDays} (${percent(perfectDays)}%)
${translatedText.reportPartialCompletion || translationKeys.reportPartialCompletion}: ${partialDays} (${percent(partialDays)}%)
${translatedText.reportSkippedDays || translationKeys.reportSkippedDays}: ${skippedDays} (${percent(skippedDays)}%)

${translatedText.reportTaskBreakdown || translationKeys.reportTaskBreakdown}
${translatedText.morningBrushing || translationKeys.morningBrushing}: ${morningCount}/${totalDays} (${percent(morningCount)}%)
${translatedText.nightBrushing || translationKeys.nightBrushing}: ${nightCount}/${totalDays} (${percent(nightCount)}%)
${translatedText.interdentalCare || translationKeys.interdentalCare}: ${flossCount}/${totalDays} (${percent(flossCount)}%)

${trend ? `${translatedText.reportTrendAnalysis || translationKeys.reportTrendAnalysis}
${translatedText.reportChangeFromPrevious || translationKeys.reportChangeFromPrevious}: ${trend.change > 0 ? '+' : ''}${trend.change}%
${translatedText.reportStatus || translationKeys.reportStatus}: ${trend.improving ? (translatedText.improving || translationKeys.improving) : (translatedText.declining || translationKeys.declining)} ↑
` : ''}

${translatedText.reportKeyInsights || translationKeys.reportKeyInsights}
${insights.map(i => `• ${i.text}`).join('\n')}

═══════════════════════════════════════
${translatedText.reportFooter || translationKeys.reportFooter}
  `;

  const downloadTxtReport = () => {
    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `smile-streak-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printReport = () => {
    window.print();
  };

  const shareViaEmail = () => {
    const subject = encodeURIComponent(translatedText.reportTitle || "My Smile Streak Dental Report");
    const body = encodeURIComponent(reportText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  // Show loading state while translating
  if (translating || Object.keys(translatedText).length === 0) {
    return (
      <div className="space-y-6 pb-8">
        <div className="bg-gradient-to-br from-blue-600 via-cyan-500 to-blue-500 text-white rounded-3xl p-6 shadow-xl">
          <div className="animate-pulse flex items-center gap-2">
            <BarChart3 className="w-6 h-6" />
            <h2 className="text-2xl font-black">Loading...</h2>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-8">
      {/* Header */}
      <div className="bg-gradient-to-br from-blue-600 via-cyan-500 to-blue-500 text-white rounded-3xl p-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -translate-y-16 translate-x-16" />
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-white/10 rounded-full translate-y-12 -translate-x-12" />
        
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-2">
            <BarChart3 className="w-6 h-6" />
            <h2 className="text-2xl font-black">{translatedText.title}</h2>
          </div>
          <p className="text-sm opacity-90">{translatedText.subtitle}</p>
        </div>
      </div>

      {/* Timeframe Selector */}
      <div className="flex gap-2 overflow-x-auto pb-2">
        {[
          { id: 'all', label: translatedText.allTime },
          { id: '30days', label: translatedText.last30Days },
          { id: '7days', label: translatedText.last7Days }
        ].map(tf => (
          <button
            key={tf.id}
            onClick={() => setTimeframe(tf.id)}
            className={`px-4 py-2 rounded-xl font-semibold whitespace-nowrap transition-all ${
              timeframe === tf.id
                ? 'bg-blue-500 text-white shadow-md'
                : 'bg-white text-gray-600 border border-gray-200 hover:border-blue-300'
            }`}
          >
            {tf.label}
          </button>
        ))}
      </div>

      {/* Overview Cards */}
      <div className="grid grid-cols-2 gap-4">
        <div className="bg-white rounded-2xl p-5 shadow-lg border border-blue-100">
          <div className="flex items-center gap-2 mb-2">
            <Calendar className="w-5 h-5 text-blue-500" />
            <p className="text-xs text-gray-500">{translatedText.totalDays}</p>
          </div>
          <p className="text-3xl font-black text-gray-900">{totalDays}</p>
        </div>

        <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-5 shadow-lg border-2 border-green-200">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle2 className="w-5 h-5 text-green-600" />
            <p className="text-xs text-gray-600">{translatedText.perfectDays}</p>
          </div>
          <p className="text-3xl font-black text-green-700">{percent(perfectDays)}%</p>
          {trend && (
            <p className={`text-xs font-semibold mt-1 flex items-center gap-1 ${
              trend.improving ? 'text-green-600' : 'text-red-600'
            }`}>
              {trend.improving ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
              {trend.change > 0 ? '+' : ''}{trend.change}% {translatedText.vsPrevious}
            </p>
          )}
        </div>
      </div>

      {/* Detailed Stats */}
      <div className="bg-white rounded-3xl p-6 shadow-lg border border-blue-100">
        <h3 className="font-black text-gray-900 mb-4">{translatedText.taskBreakdown}</h3>
        
        <div className="space-y-4">
          {[
            { label: translatedText.morningBrushing, count: morningCount, icon: "☀️", color: "orange" },
            { label: translatedText.nightBrushing, count: nightCount, icon: "🌙", color: "indigo" },
            { label: translatedText.interdentalCare, count: flossCount, icon: "🧵", color: "cyan" }
          ].map((task) => {
            const taskPercent = percent(task.count);
            return (
              <div key={task.label}>
                <div className="flex justify-between items-center mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-xl">{task.icon}</span>
                    <span className="font-semibold text-gray-900">{task.label}</span>
                  </div>
                  <span className="font-bold text-gray-900">{taskPercent}%</span>
                </div>
                <div className="relative w-full h-3 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className={`h-full bg-gradient-to-r from-${task.color}-400 to-${task.color}-500 transition-all duration-500`}
                    style={{ width: `${taskPercent}%` }}
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">{task.count} {translatedText.outOfDays} {totalDays} {translatedText.days}</p>
              </div>
            );
          })}
        </div>
      </div>

      {/* Completion Distribution */}
      <div className="bg-white rounded-3xl p-6 shadow-lg border border-blue-100">
        <h3 className="font-black text-gray-900 mb-4">{translatedText.completionDistribution}</h3>
        
        <div className="grid grid-cols-3 gap-3">
          <div className="text-center p-4 rounded-2xl bg-green-50 border border-green-200">
            <p className="text-3xl font-black text-green-600">{perfectDays}</p>
            <p className="text-xs text-gray-600 mt-1">{translatedText.perfect}</p>
            <p className="text-xs font-semibold text-green-600">{percent(perfectDays)}%</p>
          </div>
          
          <div className="text-center p-4 rounded-2xl bg-yellow-50 border border-yellow-200">
            <p className="text-3xl font-black text-yellow-600">{partialDays}</p>
            <p className="text-xs text-gray-600 mt-1">{translatedText.partial}</p>
            <p className="text-xs font-semibold text-yellow-600">{percent(partialDays)}%</p>
          </div>
          
          <div className="text-center p-4 rounded-2xl bg-red-50 border border-red-200">
            <p className="text-3xl font-black text-red-600">{skippedDays}</p>
            <p className="text-xs text-gray-600 mt-1">{translatedText.skipped}</p>
            <p className="text-xs font-semibold text-red-600">{percent(skippedDays)}%</p>
          </div>
        </div>
      </div>

      {/* Insights */}
      <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-3xl p-6 shadow-lg border-2 border-purple-200">
        <div className="flex items-center gap-2 mb-4">
          <Zap className="w-6 h-6 text-purple-600" />
          <h3 className="font-black text-gray-900">{translatedText.personalizedInsights}</h3>
        </div>
        
        <div className="space-y-3">
          {insights.map((insight, i) => (
            <div key={i} className="flex items-start gap-3 p-4 bg-white/60 backdrop-blur-sm rounded-2xl">
              <div className="flex-shrink-0 mt-0.5">{insight.icon}</div>
              <p className="text-sm text-gray-700">{insight.text}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Weekly Trend (if available) */}
      {Object.keys(weeklyData).length > 1 && (
        <div className="bg-white rounded-3xl p-6 shadow-lg border border-blue-100">
          <h3 className="font-black text-gray-900 mb-4">{translatedText.weeklyTrend}</h3>
          <div className="space-y-2">
            {Object.entries(weeklyData).slice(-4).map(([week, data]) => (
              <div key={week}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="font-semibold text-gray-700">{week}</span>
                  <span className="text-gray-600">{data.perfect} {translatedText.perfectDaysLower}</span>
                </div>
                <div className="flex h-3 rounded-full overflow-hidden bg-gray-100">
                  <div className="bg-green-500" style={{ width: `${(data.perfect / 7) * 100}%` }} />
                  <div className="bg-yellow-400" style={{ width: `${(data.partial / 7) * 100}%` }} />
                  <div className="bg-red-400" style={{ width: `${(data.skipped / 7) * 100}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export Options */}
      <div className="bg-white rounded-3xl p-6 shadow-lg border border-blue-100">
        <h3 className="font-black text-gray-900 mb-4">{translatedText.shareReport}</h3>
        
        <div className="grid grid-cols-1 gap-3">
          <button
            onClick={downloadTxtReport}
            className="flex items-center justify-between p-4 rounded-2xl bg-blue-50 border-2 border-blue-200 hover:bg-blue-100 hover:border-blue-300 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-blue-500 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
                <Download className="w-5 h-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-bold text-gray-900">{translatedText.downloadReport}</p>
                <p className="text-xs text-gray-600">{translatedText.downloadDesc}</p>
              </div>
            </div>
            <FileText className="w-5 h-5 text-gray-400" />
          </button>

          <button
            onClick={shareViaEmail}
            className="flex items-center justify-between p-4 rounded-2xl bg-green-50 border-2 border-green-200 hover:bg-green-100 hover:border-green-300 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-green-500 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
                <Mail className="w-5 h-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-bold text-gray-900">{translatedText.emailReport}</p>
                <p className="text-xs text-gray-600">{translatedText.emailDesc}</p>
              </div>
            </div>
            <Share2 className="w-5 h-5 text-gray-400" />
          </button>

          <button
            onClick={printReport}
            className="flex items-center justify-between p-4 rounded-2xl bg-purple-50 border-2 border-purple-200 hover:bg-purple-100 hover:border-purple-300 transition-all group"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-purple-500 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform">
                <Printer className="w-5 h-5 text-white" />
              </div>
              <div className="text-left">
                <p className="font-bold text-gray-900">{translatedText.printReport}</p>
                <p className="text-xs text-gray-600">{translatedText.printDesc}</p>
              </div>
            </div>
            <Printer className="w-5 h-5 text-gray-400" />
          </button>
        </div>
      </div>

      {/* Dentist Recommendation */}
      <div className="bg-gradient-to-r from-cyan-50 to-blue-50 border-2 border-cyan-200 rounded-2xl p-5">
        <div className="flex items-start gap-3">
          <CheckCircle2 className="w-5 h-5 text-cyan-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-bold text-gray-900 text-sm mb-1">{translatedText.shareWithDentist}</p>
            <p className="text-xs text-gray-600">
              {translatedText.shareWithDentistDesc}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}